spring:
  datasource:
    //driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://proddb.chasinfins.com:3306/chasinfins
    username: chasinfins_owner
    password: ChasinfinsPwd
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties: 
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.SQL: debug
    
